name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
        plone: ["60"]
        # exclude:
        #   - python: "3.7"
        #     plone: "51"
    steps:
      - uses: actions/checkout@v3
      - name: Cache eggs
        uses: actions/cache@v3
        with:
          path: eggs
          key: ${{ runner.OS }}-build-python${{ matrix.python }}-${{ matrix.plone }}
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -c constraints_plone${{ matrix.plone }}.txt
          cp test_plone${{ matrix.plone }}.cfg buildout.cfg
      - name: Install buildout
        run: |
          buildout -N -t 3
      - name: Run tests
        run: |
          bin/test-coverage
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: ${{ matrix.plone }}-${{ matrix.python }}

  coveralls_finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
